# Accessing a GPU

Deoarece există situații în care dorim să reproducem o anumită rețea neuronală, este necesar să putem să creem tensori 'random' pe care putem să îi reproducem. Aici intră în acțiune conceptul de **random seed**

In [2]:
# importing the library
import torch

# creating 2 random tensors without the random seed
print('Creating 2 random tensors without the random seed and comparing them')
tensor1 = torch.rand(4)
tensor2 = torch.rand(4)
print(tensor1)
print(tensor2)
print(tensor1 == tensor2)

# creating the constant for random seed
RANDOM_SEED = 42

# setting the random seed in PyTorch
torch.manual_seed(RANDOM_SEED)

# creating 2 random tensors with random seed
print('\nCreating 2 random tensors with random seed and comparing them')
tensor3 = torch.rand(4)

# we need to set again the seed after using 'torch.rand()'
torch.manual_seed(RANDOM_SEED)
tensor4 = torch.rand(4)
print(tensor3)
print(tensor4)
print(tensor3 == tensor4)

Creating 2 random tensors without the random seed and comparing them
tensor([0.3904, 0.6009, 0.2566, 0.7936])
tensor([0.9408, 0.1332, 0.9346, 0.5936])
tensor([False, False, False, False])

Creating 2 random tensors with random seed and comparing them
tensor([0.8823, 0.9150, 0.3829, 0.9593])
tensor([0.8823, 0.9150, 0.3829, 0.9593])
tensor([True, True, True, True])


La începutul acestui curs spuneam că o rețea neuronală poate fi alcătuită din o mulțime de tensori, iar între acești tensori există numeroase calcule, numeroase computații. Aceste calcule sunt mult mai rapide pe un GPU (placă grafică) deoarece acestea sunt special concepute pentru a realiza calcule numerice extrem de rapid. Din acest motiv, PyTorch ne permite să rulăm cod pe un `GPU` pentru a face un improvement de speed la funcționalitatea codului.

Ca să verificăm dacă avem la dispoziție o placă grafică pe care am putea să o folosim o să ne folosim de 'cuda'. Comanda care trebuie folosită este `torch.cuda.isavailable()`. Comanda de mai sus ne returnează True dacă avem un GPU disponibil pe care să îl folosim și False dacă envoironment-ul unde rulăm codul nu ne pune la dispoziție un GPU.

In [3]:
torch.cuda.is_available()

False

Nu este destul să facem doar asta pentru a ne rula codul pe un GPU. Mai există ceva ce poartă denumirea de `device agnostic code`. Este un concept destul de important în Pytorch deoarece depinzând unde anume o să rulăm codul de Python este posibil să avem la dispoziție sau să nu avem la dispoziție un GPU pe care să rulăm acest cod. Aici putem să punem condiția dacă avem un GPU atunci să îl folosim, dacă nu, atunci să folosim un CPU (un procesor).

In [6]:
device = 'cuda'

Modul prin care facem asta este să ne creem o variabilă (prin convenție, această variabilă poartă denumirea de **device**). Momentan am stabilit-o la 'cuda', dare înseamnă placă grafică (GPU). Trebuie să verificăm dacă avem la dispoziție o placă grafică și doar atunci să rulăm codul pe placa grafică, altfel o să rulăm codul pe procesoare.

In [8]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

De asemenea putem să verificăm și câte plăci grafice avem disponibile (există situații unde lucrăm cu componente din cloud și avem la dispoziție mai multe componente grafice), fiecare dintre placa putând să fie folosită pentru a rula un anumit cod specific. Pentru asta o să folosim `torch.cuda.device_count()`

In [9]:
torch.cuda.device_count()

0

Numărul returnat reprezintă numărul de plăci grafice de care dipsunem și de care ne putem folosi.

## Recapitulare

În cadrul acestui curs am învățat

1. Cum să verificăm dacă dispunem de un GPU pe care să rulăm un cod de PyTorch

```python
import torch

torch.cuda.is_available()
```

2. Cum să stabilim device-ul pe care să ruleze cod-ul de PyTorch în funcție de disponibilitatea plăcii grafice

```python
import torch

device = 'cuda' if torch.cuda.is_available else 'cpu'
```

3. Cum să verificăm numărul de GPU-uri pe care le avem la dispoziție

```python
import torch

torch.cuda.device_count()
```