# PyTorch and NumPy

În lecția precedentă am parcurs procedeul de indexare din tensori. Acest procedeu este asemănător ca și cel cu indexare din NumPy pentru un array de mai multe dimensiuni. Recapitulare:

In [3]:
# importing the library
import torch

# creating a tensor
tensor = torch.arange(1, 10).reshape(1, 3, 3)
print(tensor)

print('----------Python Style---------')
# indedxing on the 0th dimension
print(f'\nIndexing the 0th dimension: tensor[0]')
print(tensor[0])

# indedxing on the 1st dimension
print(f'\nIndexing the 1st dimension: tensor[0][0]')
print(tensor[0][0])

# indedxing on the 2nd dimension
print(f'\nIndexing the 2nd dimension: tensor[0][0][2]')
print(tensor[0][0][2])

print('---------NumPy Style----------')
# indedxing on the 0th dimension
print(f'\nIndexing the 0th dimension: tensor[0]')
print(tensor[0])

# indedxing on the 1st dimension
print(f'\nIndexing the 1st dimension: tensor[0, 0]')
print(tensor[0, 0])

# indedxing on the 2nd dimension
print(f'\nIndexing the 2nd dimension: tensor[0, 0, 2]')
print(tensor[0, 0, 2])

print('---------Using Slicing----------')
# indedxing on the 0th dimension
print(f'\nIndexing: tensor[:, : 2]')
print(tensor[:, :, 2])



tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
----------Python Style---------

Indexing the 0th dimension: tensor[0]
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Indexing the 1st dimension: tensor[0][0]
tensor([1, 2, 3])

Indexing the 2nd dimension: tensor[0][0][2]
tensor(3)
---------NumPy Style----------

Indexing the 0th dimension: tensor[0]
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Indexing the 1st dimension: tensor[0, 0]
tensor([1, 2, 3])

Indexing the 2nd dimension: tensor[0, 0, 2]
tensor(3)
---------Using Slicing----------

Indexing: tensor[:, : 2]
tensor([[3, 6, 9]])


În cadrul lecției curente o să ne utiăm peste modul cum funcționează PyTorch cu NumPy. NumPy este o librărie extrem de populară din Python care se ocupă cu operații numerice extrem de rapid. Din moment ce este o librărie super populară și are o mulțime de funcționabilități, PyTorch are anumite funcționalități prin care să interacționeze cu această librărie. De foarte multe ori este posibil să avem un set de date în formatul `numpy.ndarray` și să avem nevoie să îl transoformăm în `torch.tensor`. Există și situația inversă, unde dorim să transformăm dintr-un tensor în array un anumit set de date. Pentru fiecare dintre aceste situații există câte o rezolvare

În prima situație, cea în care dorim să transformăm din **numpy.ndarray** în **torch.tensor** avem la dispoziție metoda `torch.from_numpy()`, metodă care ia ca și argument un array de tip ndarray din NumPy. O să creem un array în NumPy și o să îl convertim într-un tensor

In [11]:
# importing the libraries
import torch
import numpy as np

# creating a NumPy ndarray
arr = np.arange(0., 10.)

In [12]:
arr

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [13]:
type(arr)

numpy.ndarray

Mai sus avem un array din NumPy pe care dorim să îl convertim într-un tensor din PyTorch. Pentru asta, după cum spuneam putem să folosim metoda **torch.from_numpy()**

In [14]:
tensor = torch.from_numpy(arr)

In [15]:
tensor

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)

In [16]:
type(tensor)

torch.Tensor

In [18]:
arr, tensor

(array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

Ceea ce putem observa după această transformare, întradevăr, datele s-au păstrat, dar tipul de date din tensor-ul creat este **float64**, tip de date care nu este ce default din PyTorch, deoarece știm că tipul de date default pentru un tensor este **float32**. Acest lucru apare deoarece tipul de date default stocat într-un array NumPy este **float64**, iar atunci când se convertește din NumPy ndarray în PyTorch tensor se preia și tipul de date din acel array. Dacă dorim putem să modificăm acest tip de date ca să fie cel standard în momentul în care facem transformarea

In [20]:
print(torch.from_numpy(arr).type(torch.float32), torch.from_numpy(arr).type(torch.float32).dtype)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]) torch.float32


Acum o să ne uităm peste al doilea caz, atunci când dorim să transformăm un tensor în array din NumPy. Pentru acest caz asupra tensor-ului pe care dorim să îl transformăm o să aplicăm metoda '.numpy()' (`tensor.numpy()`). Această metodă o să returneze un array de tip **numpy.ndarray** cu aceleași date pe care le are tensor-ul respectiv

In [21]:
# creating a tensor
tensor = torch.ones(1, 7)
tensor

tensor([[1., 1., 1., 1., 1., 1., 1.]])

In [22]:
arr = tensor.numpy()
arr

array([[1., 1., 1., 1., 1., 1., 1.]], dtype=float32)

In [23]:
tensor, arr

(tensor([[1., 1., 1., 1., 1., 1., 1.]]),
 array([[1., 1., 1., 1., 1., 1., 1.]], dtype=float32))

Din nou, putem observa că array-ul a preluat tipul de date standard din tensor. De asemenea, putem să convertim tipul de date pentru a fi standard cu cel din NumPy

In [24]:
tensor.type(torch.float64).numpy()

array([[1., 1., 1., 1., 1., 1., 1.]])

Aceste metode returnează noile tipuri de date, prin urmare acest rezultat ar trebui salvat într-o nouă variabilă. Variabilele respective nu împart același loc de memorie, prin urmare sunt independente una de alta, modificările făcute într-o vairabilă nu o să apară în alta.

## Recapitualre

în lecția prezentă am învățat următoarele:

1. Cum putem să transformăm un numpy.ndarray în torch.tensor

```python

import torch
import numpy as np

arr = np.arange(1., 10.)
tensor = torch.from_numpy(arr)
```

2. Atunci când convertim din numpy.ndarray în torch.tensor se preia și tipul de date standard din array (float64 este tipul de date standard din NumPy)

```python

arr = np.arange(1., 10.)

# changing the tensor type from float64 to float32
tensor = torch.from_numpy(arr).type(torch.float32)
```

3. Cum putem să transformăm un torch.tensor în numpy.ndarray

```python

import torch
import numpy as np

tensor = torch.ones(1, 7)
arr = tensor.numpy()
```

4. Atunci când convertim din torch.tensor în numpy.ndarray se preia și tipul de date standard din tensor (float32 este tipul de date standard din PyTorch)

```python

tensor = torch.ones(1, 7)

# changing the ndarray type from float32 to float64
arr = tensor.type(torch.float64).numpy()
```