# Introductions to tensors

Am ajuns la partea în care putem să începem să și scriem și cod de Python pentru a învăța PyTorch. Primul pas pe caree trebuie să îl facem este să ne instalăm framework-ul de PyTorch. Putem să facem asta cu pip

In [3]:
! pip3 install torch torchvision torchaudio

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.8/139.8 MB 3.7 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 1.1 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/3.9 MB 3.3 MB/s eta 0:00:0000:0100:01
  Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.5/6.5 MB 2.9 MB/s eta 0:00:0000:0100:01
  Using cached networkx-3.0-py3-none-any.whl (2.0 MB)
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
  Using cached numpy-1.24.2-cp39-cp39-macosx_10_9_x86_64.whl (19.8 MB)
  Using cached Pillow-9.4.0-2-cp39-cp39-macosx_10_10_x86_64.whl (3.3 MB)
  Using cached requests-2.28.2-py3-none-any.whl (62 kB)
  Using cached MarkupSafe-2.1.2-cp39-cp39-macosx_10_9_x86_64.whl (13 kB)
  Using cached certifi-2022.12.7-py3-none-any.whl (155 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.9/140.9 KB 2.5 MB/s eta 0:00:00a 0:00:01
  Using cached idna-3.4-py3-none-any.whl (61 kB)
   

Acum că am instalat framework-ul de PyTorch putem să îl importăm în Python utilizând comanda `import torch`

In [4]:
import torch

De asemenea putem să și vizualizăm ce versiune de PyTorch avem instalată cu comanda `print(torch.__version__)`

In [5]:
print(torch.__version__)

2.0.0


Partea mai puțin plăcut în ceea ce privește rularea de PyTorch utilizând un laptop de MacBook este faptul că nu putem utiliza componenta de `cuda` caree ne permite să rulăm cod de PyTorch pe o placă grafică ca să ne îmbunătățim performanța codului (codul rulează mai rapid pe o placă grafică (GPU) decât pe un procesor (CPU))

Peste ce o să ne uităm la început o să fie o introducere generală despre `tensori`. Un tensor reprezintă partea de bază din Deep Learning. Ca și o idee generală, un tensor reprezintă o modalitate de a reprezenta date, mai exact, date într-o formă multi-dimensională (date numerice), dar aceste date defapt reprezintă altceva (imagini, texte, etc)

Primul tip de tensor pe care o să îl creem poartă denumirea de `tensor scalar`. Deși în PyTorc orice este considerat ca și un Tensor, există mai multe tipuri diferite de tensori. O să începem cu tipul de tensor scalar. Pentru a crea un tensor o să ne folosim de sintaxa `torch.tensor()`. Din moment ce știm că un tensor conține date numerice o să îi oferim o valoare numerică (7 în cazul de față) la acest tensor

In [6]:
# creating a scalar tensor
scalar = torch.tensor(7)

In [7]:
scalar

tensor(7)

Dacă afișăm variabila respectivă observăm faptul că aceasta este o variabilă de tip tensor care are valoarea 7. Un tensor are ca și atribute importante numărul de dimensiuni și forma pe care o are acel tensor. Să verificăm ce dimensiune (`tensor.ndim`) și ce formă are (`tensor.shape`)

In [8]:
# getting the dimension of a tensor
scalar.ndim

0

In [9]:
# getting the shape of a tensor
scalar.shape

torch.Size([])

Tensor-ul scalar de mai sus are dimensiunea 0 și de asemenea valoarea tot 0 pentru forma pe care o are (pe parcurs o să vedem mai bine ce anume reprezintă aceste dimensiuni și forme). Există posibilitatea ca uneori să dorim să extragem valoarea dintr-un tensor sub formă de integer sau float. În aceste cazuri folosim metoda `tensor.item()`

In [10]:
# getting the items from a tensor
scalar.item()

7

Următorul tip de tensor peste care o să ne utiăm o să fie un `vector`. La fel ca și un tensor scalar, și acesta se creează cu linia de cod `torch.tensor()`. Care este diferența dintre un tensor scalar și un tensor vector? Diferența este la modul în care sunt stocate datele.

In [11]:
# creating a vector tensor
vector = torch.tensor([7, 7])

In [12]:
vector

tensor([7, 7])

Modul prin care putem face diferența dintre un tensor scalar și unul de tip vector este faptul că tensor-ul vector are mai multe valori, iar tensor-ul scalar are o singură valoare.

In [13]:
# getting the dimension of a vector tensor
vector.ndim

1

In [14]:
# getting the shape of a vector tensor
vector.shape

torch.Size([2])

Se poate observa și diferența între ceea ce privește dimensiunea și forma unui tensor scalar și un tensor de tip vector. Tensor-ul scalar avea valoarea 0 la dimensiune și formă, iar acest tensor de tip vector are valoare 1 la dimensiune și 2 la formă, ceea ce poate părea un pic confuz. O să înțelegem mai multe atunci când vedem tensori cu mai multe dimensiuni. O altă modalitate prin care putem să ne dăm seama câte dimensiuni are un tensor este prin numărul de paranteze pătrate. Tensor-ul scalar nu avea niciun set de paranteze pătrate (și implicit are valoare 0 la dimensiune), iar tensor-ul de tip vector are un set de paranteze drepte și valoarea 1 pentru dimensiuneae acestuia.

Dacă dorim să ducem lucrurile la următorul nivel, putem să creem un tensor de tip `matrice`. Diferența dintre un vector și o matrice (pentru tensor) este faptul că o matrice are două dimensiuni (două seturi de paranteze drepte). Să creem acest tensor de tip matrice (se creează tot cu comanda `torch.tensor()`)

In [15]:
# creating a matrix tensor
matrix = torch.tensor([[7, 8], [9, 10]])

In [16]:
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [17]:
# getting the dimensions of a matrix tensor
matrix.ndim

2

In [18]:
# getting the shape of a matrix tensor
matrix.shape

torch.Size([2, 2])

Valoare de `torch.Size([2, 2])` ne indică faptul că există două rânduri de valori, iar fiecare rând are câte două elemente

Ultimul tip de tensor care există poartă denumirea de `tensor`. Diferența dintre un `tensor` și un tensor de tip matrice este faptul că acesta se găsește în trei dimensiuni (trei seturi de paranteze drepte). Să creem acest tensor

In [20]:
# creating a tensor
tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])

In [21]:
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

În partea teoretică spuneam că un tensor poate să aibă uneori milioane de valori. Scrierea de mână a unor astfel de tensori este un proces aproape imposibil. Partea bună este faptul că de cele mai multe ori nu o să fim nevoiți să creem acești tensori de la 0, ci PyTorch o să se ocupe de conversia unor tipuri de date în tensori automat pentru noi

In [22]:
# getting the dimensions of a tensor
tensor.ndim

3

In [23]:
# getting the shape of a tensor
tensor.shape

torch.Size([1, 3, 3])

Valoarea de la tensor.shape ne spune faptul că este creat dintr-o matrice care are un shape de 3/3. Putem să verificăm asta prin accesarea primului index din cadrul acestui tensor

In [24]:
tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

Putem vedea că ceea ce a fost returnat ca fiind pe primul index din acest tensor este o matrice. Prin urmare, în cadrul unui tensor putem să avem mai multe matrici

<img src='../SS/04.png'>

Pentru o reprezentare vizuală mai bună putem să ne uităm la imaginea de mai sus. În acea imagine obserăm cum anume arată fiecare tip de tensor peste care ne-am uitat în cadrul acestui curs.

## Recapitulare

În acestă secțiune am învățat următoarele lucruri:
1. Cum putem să importăm framework-ul de PyTorch
```python
import torch
```

2. Care sunt tipurile diferite de tensori din PyTorch

    - Scalar

    - Vector

    - Matrix

    - Tensor

3. Cum putem crea un tensor de tip scalar

```python
import torch

scalar = torch.tensor(7)
```

4. Cum putem crea un tensor de tip vector

```python
import torch

vector = torch.tensor([7, 8])
```

5. Cum putem crea un tensor de tip matrice

```python
import torch

matrix = torch.tensor([[7, 8], [9, 10]])
```

6. Cum putem crea un tensor

```python
import torch

tensor = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
```

7. Care sunt atributele cu care putem să verificăm dimensiunea și forma unui tensor

```python
import torch

scalar = torch.tensor(7)
scalar.ndim # returns the dimension of a tensor
scalar.shape # return the shape of a tensor
```

8. Cum putem să extragem valorile dintr-un tensor sub formă de numere
```python
import torch

scalar = torch.tensor(7)
scalar.item() # returns the number inside the scalar tensor
```