# Matrix Multiplication

În secțiunea precedentă am văzut cum putem să realizăm anumite operații aritmetice de bază cu un anumit tensor. Să facem o scurtă recapitulare

In [2]:
# importing PyTorch
import torch

# creating a tensor
tensor = torch.tensor([1, 2, 3])

# printing the tensor
print(tensor)
print('--------------------------ADDITION--------------------------')

# Addition
print(f"Addition of a tensor using '+' sign")
print(f"tensor + 10: {tensor + 10}")

print(f"Addition of a tensor using 'torch.add()' function")
print(f"torch.add(tensor, 10): {torch.add(tensor, 10)}")

print('--------------------------SUBSTRACTION--------------------------')
# Substraction
print(f"Substraction of a tensor using '-' sign")
print(f"tensor - 10: {tensor - 10}")

print(f"Substraction of a tensor using 'torch.sub()' function")
print(f"torch.sub(tensor, 10): {torch.sub(tensor, 10)}")

print('--------------------------MULTIPLICATION--------------------------')
# Multiplication
print(f"Multiplication of a tensor using '*' sign")
print(f"tensor * 10: {tensor * 10}")

print(f"Multiplication of a tensor using 'torch.mul()' function")
print(f"torch.mul(tensor, 10): {torch.mul(tensor, 10)}")

print('--------------------------DIVISION--------------------------')
# Division
print(f"Division of a tensor using '/' sign")
print(f"tensor / 10: {tensor / 10}")

print(f"Division of a tensor using 'torch.div()' function")
print(f"torch.div(tensor, 10): {torch.div(tensor, 10)}")



tensor([1, 2, 3])
--------------------------ADDITION--------------------------
Addition of a tensor using '+' sign
tensor + 10: tensor([11, 12, 13])
Addition of a tensor using 'torch.add()' function
torch.add(tensor, 10): tensor([11, 12, 13])
--------------------------SUBSTRACTION--------------------------
Substraction of a tensor using '-' sign
tensor - 10: tensor([-9, -8, -7])
Substraction of a tensor using 'torch.sub()' function
torch.sub(tensor, 10): tensor([-9, -8, -7])
--------------------------MULTIPLICATION--------------------------
Multiplication of a tensor using '*' sign
tensor * 10: tensor([10, 20, 30])
Multiplication of a tensor using 'torch.mul()' function
torch.mul(tensor, 10): tensor([10, 20, 30])
--------------------------DIVISION--------------------------
Division of a tensor using '/' sign
tensor / 10: tensor([0.1000, 0.2000, 0.3000])
Division of a tensor using 'torch.div()' function
torch.div(tensor, 10): tensor([0.1000, 0.2000, 0.3000])


Un lucru pe care nu l-am parcurs în lecția precedentă este cum facem operații de doi tensori care au mai multe valori (același număr de valori), care este conceptul care se aplică în acest caz. Ei bine, să luăm exemplul de înmulțire, aici se aplică conceptul de 'element-wise multiplication' unde prima valoare din primul tensor este înmulțit cu prima valoare din al doilea tensor, a doua valoare din primul tensor este înmulțită cu a doua valoare din al doilea tensor și tot așa

In [7]:
# Multiplication of tensors with multiple values (the same length)
print(f'Working with tensor {tensor}')
print(f'tensor * tensor')
print(f'Equals: {tensor * tensor}')

Working with tensor tensor([1, 2, 3])
tensor * tensor
Equals: tensor([1, 4, 9])


După cum spuneam, fiecare valoare se înmulțește cu valoare de pe același index din ambii tensori.

Cea mai comună operație între tensori care se găsește poartă denumirea de `Matrix Multiplication` (mai poartă denumirea și de 'dot product'). Atunci când am făcut operația de multiplicare pentru un tensor cu o singură valoare, conceptul este destul de ușor, se ia valoarea respectivă și se înmulțește cu fiecare element din tensor. Am verificat acest lucru cu un tensor de tip vector, dar din moment ce suntem la capitolul 'Matrix Multiplication' putem să încercă să realizăm această operație și cu un tensor de tip matrice (o să vedem că este același concept)

In [4]:
# creating a matrix tensor
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [5]:
# multiplying a matrix tensor by a single value
matrix * 10

tensor([[10, 20, 30],
        [40, 50, 60]])

După cum spuneam, conceptul este același, se înmulțește fiecare elemement din matrice cu valoare 10. Complexitatea apare atunci când dorim să multiplicăm două matrici (Matrix Multiplication). Pentru asta trebuie să facem cum am spus ceea ce poartă denumirea de `dot-product`. Acest concept arată așa:

<img src='../SS/05.png' width=700>

Deși poartă denumirea de 'Matrix Multiplication' putem să facem acest procedeu și pentru tensori de tip vector. Să facem această operație de 'Matrix Multiplication' pentru tensor-ul cu care am lucrat mai sus (în care am înmulțit un tensor cu el însuși)

In [8]:
tensor * tensor

tensor([1, 4, 9])

Operația de mai sus este 'element-wise'. Pentru a face 'Matrix Multiplication' o să folosim comanda din PyTorch `torch.matmul()`. Să vedem ce rezultat obținem

In [9]:
torch.matmul(tensor, tensor)

tensor(14)

Rezultatul de la 'torch.matmul()' dintre același tensor este 14. Cum anume se ajunge la acest rezultat? Pentru partea de element-wise am zis că se înmulțește prima valoare din primul tensor cu prima valoare din al doilea tensor și accea este trecută ca și primă valoare din tensorul care rezultă. Pentru partea de matrix multiplication se procedează în mare măsură la fel, se înmulțește prima valoare din primul tensor cu prima valoare din al doilea matrix, iar acea valoare se adună cu rezultatul înmulțirii dintre a doua valoare din primul tensor și a doua valoare din al doilea tensor, și tot așa până ce se ajunge la finalul operațiilor de înmulțire cu fiecare valoare din tensori.

Pentru explicația matematică:

tensor1 = [1, 2, 3]

tensor2 = [1, 2, 3]

1 * 1 = 1 (primul element din primul tensor înmulțit cu primul element din al doilea tensor)

2 * 2 = 4 (al doilea element din primul tensor înmulțit cu al doilea element din al doilea tensor)

3 * 3 = 9 (al treilea element din primul tensor înmulțit cu al treilea element din al doilea tensor)

1 + 4 + 9 = 14 - de aici a rezultat valoarea 14 din 'torch.matmul(tensor, tensor)'


In [10]:
(1 * 1) + (2 * 2) + (3 * 3)

14

Pentru exemplul din imagine unde avem cele două matrici și rezultatul pentru primul calcul, acesta este reprezentat matematic astfel

In [11]:
(1 * 7) + (2 * 9) + (3 * 11)

58

Pentru mai multe informații referitor la cum funcționează partea de Matrix Multiplication putem să accesăm link-ul https://www.mathsisfun.com/algebra/matrix-multiplying.html

Exemplul de mai sus este realizat cu înmulțirea unui tensor cu el însuși, un tensor extrem de mic, de asemenea. În momentul în care lucrăm cu o rețea neuronală, acești tensori sunt de mărimi considerabile, iar apariția erorilor când facem operația de matrix multiplication este una extrem de des întâlnită. Din acest motiv există două reguli importante în ceea ce privește Matrix Multiplication

1. **inner dimesions** de la cei doi tensor trebuie să fie la fel

    - tensor([3, 2]) @ tensor([3, 2]) # o să rezulte într-o eroare

    - tensor([3, 2]) @ tensor([2, 3]) # o să funcționeze

2. Tensorul de tip matrice ce rezultă o să aibă forma de  la **outer dimensions**

Ce înseamnă prima regulă? Atunci când facem **Matrix Multiplication** pentru doi tensori, valorile cele mai apropiate (inner), adică a doua valoare de la primul tensor și prima valoarea de la al doilea tensor trebuie să fie identice pentru a putea să multiplicăm aceste matrici

In [12]:
torch.matmul(torch.rand(size=(3, 2)), torch.rand(size=(3, 2)))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

Din moment ce cele două valori de la inner dimensions nu sunt la fel, atunci codul rezultă într-o eroare

In [13]:
torch.matmul(torch.rand(size=(3, 2)), torch.rand(size=(2, 3)))

tensor([[0.2816, 0.2249, 0.2578],
        [0.3008, 0.4791, 0.1950],
        [0.4320, 0.5140, 0.3385]])

Atunci când cele două valori de la inner dimensions sunt aceleași (ambele au valoare 2), atunci putem să realizăm procesul acesta de multplicare de matrici. După cum se observă, tensorul de tip matrice ce a rezultat are forma de la **outer dimesions**, adică prima valoare din shape de la primul tensor și utlima valoare din shape de la al doilea tensor (valorile cele mai depărtate)

O altă modalitae de a executa operația de multiplicare de matrici este prin utilizarea semnului `@` între cei doi tensor (**tensor1 @ tensor2**)

In [14]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

În exemplele de **Matrix Multiplication** peste care ne-am uitat mai sus am oferit ca și valori doi tensori pe care i-am creat utilizând 'torch.rand()' la care am putut specifica forma pe care să o aibă astfel încât să putem fie să reproducem eroarea, fie să avem un rezultat corect. Ce facem însă în situația în care deja avem doi tensor?

In [15]:
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

Cei doi tensori sunt deja creați și dorim să îi multiplicăm, dar valorile de la **inner dimensions** nu corespund. Pentru a rezolva această problemă există conceptul de `transpose`. Prin acest concept putem să modificăm axele (forma) unui tensor. Dintr-un tensor ce are forma (3, 2), dacă utilizâm conceptul de **transpose** putem să îl transformăm într-un tensor de forma (2, 3). Pentru a realiza asta, trebuie doar să apelăm atributul `.T` pentru tensor-ul asupra căruia dorim să facem transpose

In [16]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

Atunci când facem transpose la un tensor, acesta nu își pierde din date, ci doar pur și simplu datele sunt rearanjate în altă formă. Acum la comanda de **torch.matmul()** să îi oferim ca și al doilea parametru acest tensor pe care l-am transpus

In [18]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Ca să vedem și mai bine de ce o comandă a mers și una nu, o să accesăm shape-ul acestor tensori

In [20]:
print(f'Shape of tensor_A: {tensor_A.shape}')
print(f'Shape of tensor_B: {tensor_B.shape}')
print(tensor_A.shape, tensor_B.shape)

Shape of tensor_A: torch.Size([3, 2])
Shape of tensor_B: torch.Size([3, 2])
torch.Size([3, 2]) torch.Size([3, 2])


Deoarece acești doi tensori nu au acceași valoare la **inner dimension** nu putem să îi multiplicăm

In [21]:
print(f'Shape of tensor_A: {tensor_A.shape}')
print(f'Shape of tensor_B.T: {tensor_B.T.shape}')
print(tensor_A.shape, tensor_B.T.shape)

Shape of tensor_A: torch.Size([3, 2])
Shape of tensor_B.T: torch.Size([2, 3])
torch.Size([3, 2]) torch.Size([2, 3])


Acum că am făcut transpose la tensor_B, valorile de la **inner dimensions** corespund, prin urmare putem realizăm multiplicarea între acești doi tensori

## Recapitulare

În cadrul acestei secțiuni am învățat:

1. Ce se întâmplă atunci când realizăm multiplicare între doi tensori de tip vector cu aceeași dimensiune

    Valorile sunt multiplicate sub forma 'element-wise'

    tensor1 = [1, 2, 3], tensor2 = [2, 3, 4]

    - 1 * 2 = 2

    - 2 * 3 = 6

    - 3 * 4 = 12

    tensor_final = ([2, 6, 12])

2. Cum putem să folosim Matrix Multiplication cu PyTorch

    ```python
    import torch

    tensor1 = torch.tensor([1, 2, 3])
    tensor2 = torch.tensor([2, 3, 4])

    tensor_final = torch.matmul(tensor1, tensor2)
    ```

3. Cum funcționează conceptul de Matrix Multiplication

    - 1 * 2 = 2

    - 2 * 3 = 6

    - 3 * 4 = 12

    2 + 6 + 12 = 20

    tensor_final = ([20])

4. Care sunt cele două reguli pentru Matrix Multiplication

    a. **inner dimesions** de la cei doi tensor trebuie să fie la fel

    - tensor([3, 2]) @ tensor([3, 2]) # o să rezulte într-o eroare

    - tensor([3, 2]) @ tensor([2, 3]) # o să funcționeze

    b. Tensorul de tip matrice ce rezultă o să aibă forma de  la **outer dimensions**

5. Cum putem să facem transpose la un tensor pentru a îi modifica shape-ul

    ```python
    import torch

    tensor = torch.rand(size=3, 2)
    # tensor has the shape (3, 2)

    tranpose_tensor = tensor.T
    # transpose_tensor has the shape (2, 3) and the same values
    ```