# Reshaping, stacking, squeezing and unsqueezing

În ultima parte am văzut cum putem să utilizăm funcțiile de agregare pentru tensori (să aflăm valoarea cea mai mare, cea mai mică, media, suma, etc.). Dintre aceste metode, cea de **mean()** este diferită deoarece această funcționează doar cu date de tip float32

In [3]:
# importing PyTorch
import torch

tensor = torch.arange(1, 100, 10)

# finding the max and min
print('----------MAX----------')
print(torch.max(tensor))
print(tensor.max())

print('----------MIN----------')
print(torch.min(tensor))
print(tensor.min())

print('----------ARGMAX----------')
# finding the index of max and min
print(torch.argmax(tensor))
print(tensor.argmax())

print('----------ARGMIN----------')
print(torch.argmin(tensor))
print(tensor.argmin())

print('----------SUM----------')
# finding the sum
print(torch.sum(tensor))
print(tensor.sum())

print('----------MEAN----------')
# finding the mean
# we need to modify the datatype for this
print(torch.mean(tensor.type(torch.float32)))
print(tensor.type(torch.float32).mean())

----------MAX----------
tensor(91)
tensor(91)
----------MIN----------
tensor(1)
tensor(1)
----------ARGMAX----------
tensor(9)
tensor(9)
----------ARGMIN----------
tensor(0)
tensor(0)
----------SUM----------
tensor(460)
tensor(460)
----------MEAN----------
tensor(46.)
tensor(46.)


În cadrul acestei lecții o să ne uităm peste anumite metode din PyTorch prin care putem să modificăm forma sau dimensiunea unui tensor deoarece una dintre cele mai comune erori primite din Deep Learning are legătură cu forma pe care o are un tensor, iar din acest motiv trebuie să înțelegem cum am putea să modificăm forma pe care o are un tensor pentru a rezolva problema. Metodele peste care o să ne uităm sunt următoarele:

1. Reshaping = modifică forma unui tensor după o formă pe care o definim

2. View = returnează un view (precum în SQL) al unui tensor de input cu o formă pe care o definim, dar păstrează același loc în memorie precum tensor-ul original

3. Stacking = combină mai mulți tensori adăugându-i fie pe verticală (vstack) fie pe orizontală (hstack)

4. Squeezing = elimină toate dimesniunile de tip **1** dintr-un tensor

5. Unsqueezing = adaugă o dimensiune de tip **1** la un tensor

6. Permute = retunrează un view pentru input-ul oferit cu dimensiuni permutate (schimbate) într-un anumit mod

Toate metodele de mai sus au într-un anumit mod rolul de a modifica forma (shape-ul) și dimensiune (ndim) unui tensor. O să începem prin a crea un tensor și a vedea cum putem utiliza aceste metode.

In [4]:
import torch

tensor = torch.arange(1., 10.)
tensor

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

O să începem cu metoda `reshape()`. Acestui tensor de mai sus o să încercăm să îi mai atribuim încă o dimensiune. Tensor-ul de mai sus are un singur set de paranteze drepte, prin urmare o singură dimensiune. O să îcercăm să modificăm acest tensor de tip vector (cum este acuma) într-un tensor de tip matrice (să îi mai adăugăm o dimensiune extra)

In [5]:
tensor.ndim

1

In [6]:
tensor.reshape(1, 7)

RuntimeError: shape '[1, 7]' is invalid for input of size 9

Eroarea de mai sus apare deoarece încercăm să înghesuim nouă elemente (câte are tensor-ul) într-un nou tensor care are forma de (1, 7), formă care poate conține doar 7 elemente, din acest motiv apare eroarea respectivă. Regula pe care trebuie să o urmăm atunci când facem reshape este cea cum că forma pe care o oferim la reshape să fie compatibilă cu forma inițială. Dacă înlocuim acel 7 cu un 9, atunci o să putem face resape la acel element

In [8]:
tensor.reshape(1, 9)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

Care este diferența dintre acest tensor și cel iniția? Diferența este la dimensiunea acestui tensor și la forma pe care o are

In [9]:
print(f'Original tensor ndim: {tensor.ndim}')
print(f'Original tensor shape: {tensor.shape}')

print(f'Reshaped tensor ndim: {tensor.reshape(1, 9).ndim}')
print(f'Reshaped tensor shape: {tensor.reshape(1, 9).shape}')

Original tensor ndim: 1
Original tensor shape: torch.Size([9])
Reshaped tensor ndim: 2
Reshaped tensor shape: torch.Size([1, 9])


Putem vedea că acestui tensor i s-a mai adăugat încă o dimensiune. Tensor-ul inițial are nouă elemente, prin urmare putem să îi facem un reshape cu un tensor care are tot nouă elemente (pe câte dimensiuni dorim). O să îi facem un reshape pe două dimensiuni, având forma (3, 3), deoarece 3x3=9, numărul de elemente care sunt prezente în tensor

In [10]:
tensor.reshape(3, 3)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

O să trecem acuma la `view`. Un view se creează cum se face partea de **reshape()**, o să îi oferim o nouă formă compatibilă cu tensor-ul asupar căruia aplicăm această metodă, diferența dintre 'reshape' și 'view' este faptul că un 'view' împarte aceeași memorie cu tensor-ul de bază.

In [11]:
view = tensor.view(3, 3)
view

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

Ce efect are acest fapt? Atunci când modificăm valoarea de la 'view' se modifică și tensor-ul inițial deoarece împart aceeași memorie

In [24]:
view[0][0] = 5

In [25]:
view


tensor([[5., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [26]:
tensor

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

Am modificat prima valoare din variabila 'view', dar din moment ce aceasta împarte aceeași memorie, atunci se modifică și tensor-ul inițial. Mai departe o să trecem la procedeul de `stacking`. Acest procedeu combină mai mulți tensor fie pe verticală, fie pe orizontală. Regula care stăm la baza acestei metode este faptul că acești tensor trebui să aibă aceeași formă și dimensiune. Există mai multe modalități de a combina tensori, iar aceste modalități se specificăm prin modificarea parametrului de `dim`. Acesta este setat inițial la 0, dar putem să îi modificăm valoarea pentru a vedea ce rezultate (sau erori) produce. Modul prin care trebuie să specificăm tensorii pe care dorim să îi combinăm este printr-o listă.

In [27]:
torch.stack([tensor, tensor, tensor, tensor], dim=0)

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [28]:
torch.stack([tensor, tensor, tensor, tensor], dim=1)

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [29]:
torch.stack([tensor, tensor, tensor, tensor], dim=2)

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

Parametrul **dim=0** o să facă după cum putem vedea o combinare verticală a acestor tensori, iar **dim=1** realizează combinarea tensorilor pe orizontală. Tensor-ul cu care am lucrat nu ne permită să creem un tensori combinat cu valoarea **dim=2**, dbin cauza formei și dimensiunii pe care o are acesta. Ca să înțelegem cât mai bine cum funcționează `torch.stack()` fie cătuăm documentații pe internet despre acest subiect, fie mai exeprimentăm cu diferite valori pentru forma și dimensiunea unui tensor.

În continuare o să ne utiăm peste comanda `torch.squeeze()`, comandă care elimină toate dimensiunile de valoare 1 (single dimension) dintr-un tensor

In [30]:
tensor

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [31]:
tensor.shape

torch.Size([9])

In [32]:
tensor_reshaped = tensor.reshape(1, 9)

In [34]:
tensor_reshaped.shape

torch.Size([1, 9])

O să lucrăm cu acest tensor pentru care am făcut 'reshape'. Tensor-ul de mai sus are valoarea 2 pentru tensor_reshaped.ndim și valoarea (1, 9) ca și formă. Ce o să se întâmple atunci când utilizăm comanda `tensor.squeeze()`? Definiția acestei metode ne spune că șterge toate dimensiunile cu valoare 1 dintr-un tensor. Tensor-ul de mai sus are două dimensiuni, a câte 1 și 9 elemente, prin urmare, dacă aplicăm această metodă ar trebui să ne șteargă dimensiunea cu valoarea 1

In [35]:
tensor_reshaped.squeeze().shape

torch.Size([9])

Din output-ul de mai sus reiese ceea ce se spune în definiție, se poate observa faptul că acum tensor-ul are doar o dimensiune de 9 elemente, dimensiunea cu 1 element a fost ștearsă

In [37]:
print(f'Original tensor: {tensor_reshaped}')
print(f'Squeezed tensor: {tensor_reshaped.squeeze()}')

Original tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Squeezed tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])


Se poate observa fapul că la tensor-ul la care am aplicat metoda `squeeze()` îi lipsește un set de paranteze drepte (îi lipsește o dimensiune). În ceea ce privește partea de `unsqueeze()`, această metodă adaugă o dimensiune cu valoarea 1 la tensor-ul pentru care apelăm această metodă. O să salvăm rezultatul de la la metoda de **squeeze*()** într-un tensor și după o să ne folosim de acel tensor

In [38]:
squeezed_tensor = tensor_reshaped.squeeze()
squeezed_tensor

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

Acestui tensor o să îi mai adăugăm acuma o dimensiune de valaorea 1. Pentru asta, la metoda de `tensor.unsqueeze()` trebuie să îi oferim parametrul **dim**, iar ca și valoare să îi oferim zona unde dorim să punem această dimensiune

In [42]:
squeezed_tensor.unsqueeze(dim=0), squeezed_tensor.unsqueeze(dim=0).shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [43]:
squeezed_tensor.unsqueeze(dim=1), squeezed_tensor.unsqueeze(dim=1).shape

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

Ultima metodă la care o să ne uităm o să fie cea de `torch.permute()`, iar aceasta ne permită să rearanjăm dimensiunile unui anumit tensor. Dacă avem un tensor cu valoarea (3, 2) la dimensiuni, cu metoda `torch.permute()` putem să modificăm tensor-ul astfel încât forma acestuia să fie (2, 3)

O să creem un tensor random care are forma de (3, 2)

In [46]:
tensor = torch.rand(3, 2)
print(tensor)
print(f'tensor.shape = {tensor.shape}')

tensor([[0.2698, 0.8419],
        [0.0867, 0.8942],
        [0.4671, 0.0929]])
tensor.shape = torch.Size([3, 2])


Ca să modificăm shape-ul din (3, 2) în (2, 3) o să utilizăm metoda `permute()`. Acestei metode trebuie să îi oferim ca și valori index-urile pe care se găsesc cele două dimensiuni ale tensor-ului. Dimensiunea cu 3 elemente se găsește pe index-ul 0, iar cea cu două, pe index-ul 1. Aceste două valori trebuie să le oferim metodei respective. Ordinea în care le oferim o să reprezinte nouă ordine a dimensiunilor. Dacă oferim valorile în ordinea (0, 1), atunci nu am modificat nimic deoarece dimensiunea de pe index-ul 0 rămâne tot pe index-ul 0. Ca să facem o modificare trebuie să oferim acele valori în altă ordine ordinea care este disponibilă este (1, 0), adică dimensiunea de pe index-ul 0 al tensor-ului oferit ca și input acum o să fie pe index-ul 1 al noului tensor

In [48]:
print(f'tensor: \n{tensor}')
print(f'tensor shape: {tensor.shape}')
print(f'\n permuted tensor: \n{tensor.permute(1, 0)}')
print(f'permuted tensor shape: {tensor.permute(1, 0).shape}')

tensor: 
tensor([[0.2698, 0.8419],
        [0.0867, 0.8942],
        [0.4671, 0.0929]])
tensor shape: torch.Size([3, 2])

 permuted tensor: 
tensor([[0.2698, 0.0867, 0.4671],
        [0.8419, 0.8942, 0.0929]])
permuted tensor shape: torch.Size([2, 3])


Această operațiune de permutare aprare de cele mai multe ori la prelucrarea de imagini, și anume la modificare locației dimensinulor în ceea ce privește color channels. Uneori încărcăm o imagine sub forma (244, 244, 2) ->(height, width, color_channels) și trebuie să avem datele în formatul (3, 244, 244) -> (color_channels, height, width). 

In [49]:
# creating a random tensor with dimensions and size as an image
image_shape_tensor = torch.rand(224, 224, 3) # [height, width, color_channels]

# permuting the dimensions of the tensor
permuted_image_shape_tensor = image_shape_tensor.permute(2, 0, 1)

In [50]:
print(f'Original tensor as image: {image_shape_tensor.shape}')
print(f'Permuted tensor as image: {permuted_image_shape_tensor.shape}')

Original tensor as image: torch.Size([224, 224, 3])
Permuted tensor as image: torch.Size([3, 224, 224])


## Recapitulare

În cadrul acestei secțiuni am învățat următoarele:

1. Cum să facem reshape la forma unui tensor

```python
import torch

tensor = torch.arange(1., 10.)
# the tensor has 9 elements, we only can reshape it to a tensor that also has nine elements (in whatever dimensions)
tensor.reshape(1, 9)
tensor.reshape(9, 1)
tensor.reshape(3, 3)
```

   - Forma din reshape trebuie să fie compatibilă cu forma tensorului inițial


2. Cum să creem un view pentru un tensor (aici putem să îi modificăm și shape-ul tensorului)

```python
import torch

tensor = torch.arange(1., 10.)
view_tensor = tensor.view(3, 3)
```
- Diferența dintre reshape și view este faptul că un view împarte aceeași memorie cu tensor-ul inițial, prin urmare orice modificare se va face în view o să apară și în tensor-ul inițial

3. Cum să facem stack la mai mulți vectori

```python
import torch

tensor = torch.arange(1., 10.)

v_stacked_tensors = torch.stack([tensor, tensor, tensor, tensor], dim=0) # vstack
h_stacked_tensors = torch.stack([tensor, tensor, tensor, tensor], dim=1) # hstack
```

- Tensorii din torch.stack() trebuie să aibă aceeași formă

4. Cum să facem squeeze la un tensor

```python
import torch

tensor = torch.rand(size=(1, 9))
squeezed_tensor = tensor.squeeze() # removes the 1 dimension from the tensor
```

5. Cum să facem unsqueeze la un tensor

```python
import torch

tensor = torch.arange(1., 10.)
unsqueezed_tensor = tensor.unsqueeze(dim=0)
unsqueezed_tensor = tensor.unsqueeze(dim=1)
```

6. Cum să facem permute la un tensor

```python
import torch

tensor = torch.rand(size=(244, 244, 3))
permuted_tensor = tensor.permute(2, 0, 1)
```