# Creating Tensors

În lectura precedentă am învățat care sunt diferitele tipuri de tensori din PyTorch, care e diferența dintre acestea și cum le putem crea. O să trecem printr-o scurtă recapitulare a acestora

In [3]:
# importing PyTorch
import torch

# creating a scalar tensor
print('---------SCALAR--------')
scalar = torch.tensor(7)
print(scalar)
# printing the scalar tensor attributes
print(scalar.ndim)
print(scalar.shape)

# creating a vector tensor
print('---------VECTOR--------')
vector = torch.tensor([7, 8])
print(vector)
# printing the vector tensor attributes
print(vector.ndim)
print(vector.shape)

# creating a matrix tensor
print('---------MATRIX--------')
matrix = torch.tensor([[7, 8], [9, 10]])
print(matrix)
# printing the matrix tensor attributes
print(matrix.ndim)
print(matrix.shape)

# creating a tensor
print('---------TENSOR--------')
tensor = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
print(tensor)
# printing the tensor attributes
print(tensor.ndim)
print(tensor.shape)


---------SCALAR--------
tensor(7)
0
torch.Size([])
---------VECTOR--------
tensor([7, 8])
1
torch.Size([2])
---------MATRIX--------
tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])
---------TENSOR--------
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
3
torch.Size([1, 3, 3])


În continuare o să învățăm cum putem să creem `random tensors`. De ce trebuie să creem astfel de tensori? După cum am văzut, ca să creem un tensor trebuie să fim atenți la modul în care punem seturile de paranteze drepre și totodată trebuie ca fiecare elemente din matrice să aibă același număr de valori, iar fiecare matrice dintr-un tensor să aibă același număr de valori, ceea ce uneori poate fi destul de solicitant dacă nu suntem atenți atenți când creem acest tensor

De asemenea, `random tensors` sunt importanți deoarece modul prin care foarte multe rețele neuronale învață, aceste încep cu anumiți tensori care conțin valori random (numere) și în momentul în care o rețea neuronală învață ele ajustează acele numere pentru a putea reprezenta cât mai bine datele respective. Modul în care cele mai multe rețele neuronale funcționează este următorul:

`Încep cu date random  -> se uită peste date -> updatează datele -> se uită peste date -> updatează datele ...`

După cum spuneam, nu trebuie să creem noi manual acei tensori (uneori sunt extrem de complicați și de mari), PyTorch se ocupă de partea de generare de tensori din anumite date. Un mod prin care putem genera astfel de tensori este prin folosirea comenzii `torch.rand()` ce o să returneze un tensor random. Această metodă ia ca și input valori pentru shape-ul pe care dorim să îl aibă. Numărul de valori pe care îl oferim o să ne returneze diferite tipuri de tensori. Dacă oferim o singură valoare o să ne genereze un tensor de tip vector (deoarece un tensor de tip vector are o singură dimensiune, iar din moment ce am oferit doar o valoare, ne poate crea un tensor cu o singură dimensiune). O să creem un tensor de tip matrice

In [4]:
# creating a tensor with random values
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.0575, 0.9054, 0.0655, 0.7526],
        [0.0454, 0.0762, 0.4338, 0.0785],
        [0.5706, 0.5184, 0.1153, 0.6791]])

Datele care sunt create în cadrul acestui tensor sunt valori cuprinse între 0 și 1, valori de tip float. Utilizând valorile (3, 4) în momentul în care am creat acest tensor random, asta înseamnă că o să ne creeze un tensor de tip matrice cu 3 rânduri în care fiecare rând o să aibă câte 4 valori. Putem să verificăm ce dimensiune și ce formă are acest tensor

In [5]:
# getting the dimensions of a tensor
random_tensor.ndim

2

In [6]:
# getting the shape of a tensor
random_tensor.shape

torch.Size([3, 4])

Cu ajutorul acestei metode putem să creem un tensor care are forma unei imagini. O imagine are o formă de tipul (color channels, height, width), unde:

 - color channels: reprezintă numărul de canale de culori (o imagine de obicei are următoarele canale Red-Green-Blue)

 - height: înălțimea imaginii

 - width: lățimea imaginii respective

In [7]:
# creating a tensor wiht a shape of an image
random_image_size = torch.rand(size=(3, 1024, 712))

Comanda de mai sus creează un tensor care are 3 dimensiuni (câte o dimensiune pentru fiecare canal de culori), iar ca și formă, fiecare dimensiune este de 1024x712 (care defapt reprezintă pixelii imaginii).

O altă metodă prin care putem să creem un tensor de dimensiuni mai mari, reprezintă crearea de tensori care au doar valoarea 0 sau doar valoarea 1. De cele mai multe ori, dintre acestea, cel mai des este folosit tensor-ul care are valoarea 0, deoarece acesta poate fi utilizat ca și un mask în procesarea imaginilor. Pentru a crea un tensor de valori 0 să folosim metoda `torch.zeros()` căruia îi oferim paramterul de size care este o tuplă ce reprezintă dimensiunea acestui tensor. 

In [8]:
# creating a tensor of all zeros
zeros_tensor = torch.zeros(size=(5, 7))
zeros_tensor

tensor([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]])

Un alt atribut important al unui tensor este `tensor.dtype`. Prin acest atribut se retunrează tipul de date ce este stocat în cadrul unui tensor. La crearea unui tensor, dacă nu se specifică tipul de date, acesta o să fie mereu float32

In [10]:
zeros_tensor.dtype

torch.float32

După cum putem crea un tensor cu valori doar de 0, există și o modalitate prin care putem crea un tensor cu valori doar de 1 folosind metoda `torch.ones()`

In [11]:
ones_tensor = torch.ones(size=(4, 3))
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

Alte două concepte destul de des întâlnite atunci când lucrăm cu PyTorch reprezintă crearea unui tensor folosind un range (`torch.arange()`) sau crearea a ceea ce poartă denumirea de `tensors-like`. O să începem cu un crearea unui tensor folosind metoda `torch.arange()` (care ne creează un tensor în funcție de un range)

In [13]:
# creating a range tensor
range_tensor = torch.arange(1, 10)
range_tensor

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

Metoda `torch.arange()` are trei parametrii importanți, și anume 'start', 'end' și 'step'. 'start' reprezintă valoarea de la care să înceapă acest range, 'end', valoarea la care să se oprească (nu include valoarea care este atribuită acestui parametru), iar 'step' reprezintă valoarea acelui step, adică din cât în cât să sară peste numerele dintre start și end

In [20]:
# creatig a range tensor with a step
range_step_tensor = torch.arange(start=0, end=20, step=2, dtype=float)
range_step_tensor

tensor([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.], dtype=torch.float64)

Conceptul de `tensors like` face referile la crearea unui tensor de anumite valori (zero, unu, random) după forma unui alt tensor. Pentru a crea acești tensor există metodele :

- `torch.zeros_like()`

- `torch.ones_like()`

- `torch.rand_like()`

In [21]:
rand_like_tensor = torch.rand_like(input=range_step_tensor)
rand_like_tensor

tensor([0.0247, 0.2258, 0.6461, 0.2649, 0.2872, 0.5210, 0.7848, 0.3192, 0.8036,
        0.6086], dtype=torch.float64)

In [22]:
zeros_like_tensor = torch.zeros_like(input=range_step_tensor)
zeros_like_tensor

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=torch.float64)

In [24]:
print(zeros_like_tensor.ndim)
print(range_step_tensor.ndim)
print(zeros_like_tensor.shape)
print(range_step_tensor.shape)

1
1
torch.Size([10])
torch.Size([10])


După cum se poate observa mai sus, atunci când creem un `tensor like` acesta se creează utilizând aceeași dimensiune și formă ca și tensor-ul pe care l-am folosit ca și input. Este foarte important totuși să fim siguri că tipul de date care este în tensor-ul de început să poată fi introdus în tensor-ul care se creează. De exemplu, dacă creem un tensor cu metoda 'torch.arange()' această metodă creează un tensor ce are date de tip integer în interiorul acestui, iar dacă dorim să utilizăm metoda `torch.rand_like()` unde introducem ca și input acel tensor creat de metoda 'torch.arange()' atunci o să primim o eroare deoarece când creem un 'tensor like' acesta copiază și tipul de date din tensor-ul de input, iar atunci când creem un tensor cu valori random, acesta creează valori float cuprinse între 0 și 1

In [25]:
arange_tensor = torch.arange(0, 11)
print(arange_tensor)
print(arange_tensor.dtype)
arange_like_tensor = torch.rand_like(input=arange_tensor)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
torch.int64


RuntimeError: "check_uniform_bounds" not implemented for 'Long'

Dacă dorim să creem un 'tensor-like' cu valori de 0 sau 1, atunci eroarea respectivă nu o să mai apară deoarece putem crea valori de 0 sau de 1 fie integer, fie float

In [27]:
arange_tensor = torch.arange(0, 11)
print(arange_tensor)
print(arange_tensor.dtype)
arange_like_tensor_zeros = torch.zeros_like(input=arange_tensor)
arange_like_tensor_zeros

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
torch.int64


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Recapitulare

În cadrul acestei secțiuni am învățat următoarele:

1. Cum să creem un tensor cu valori random. Acest tip de tensori este extrem de des utilizat cu PyTorch deoarece există foarte multe rețele neuronale care încep că astfle de tensori ce sunt alcătuiți din valori random

```python
import torch

random_tensor = torch.rand(size=(4, 3))
```

2. Cum să creem tensori de o structură specificată cu valori de 0 sau de 1. Tensorii cu valori de 0 sunt cei mai des utilizați, aceștia pot fi utilizați pentru a crea un mask

```python
import torch

ones_tensor = torch.ones(size=(2, 4, 6))
zeros_tensor = torch.zeros(size=(5, 8))
```

3. Cum să creem tensori folosind un range

```python
import torch

arange_tensor = torch.arnage(start=0, end=100, step=13)
```

4. Cum să creem tensori de tipul tensor-like. Acești tip de tensori copiază structura unui alt tensor (dimensiunea, forma, tipul de date stocat)

```python
import torch

arange_tensor = torch.arange(start=0, end=11)
# creating a tensor with the structure of 'arange_tensor' but full with zeros
arange_like_zeros_tensor = torch.zeros_like(input=arange_tensor)
```

