# Accessing a GPU

Deoarece există situații în care dorim să reproducem o anumită rețea neuronală, este necesar să putem să creem tensori 'random' pe care putem să îi reproducem. Aici intră în acțiune conceptul de **random seed**

In [2]:
# importing the library
import torch

# creating 2 random tensors without the random seed
print('Creating 2 random tensors without the random seed and comparing them')
tensor1 = torch.rand(4)
tensor2 = torch.rand(4)
print(tensor1)
print(tensor2)
print(tensor1 == tensor2)

# creating the constant for random seed
RANDOM_SEED = 42

# setting the random seed in PyTorch
torch.manual_seed(RANDOM_SEED)

# creating 2 random tensors with random seed
print('\nCreating 2 random tensors with random seed and comparing them')
tensor3 = torch.rand(4)

# we need to set again the seed after using 'torch.rand()'
torch.manual_seed(RANDOM_SEED)
tensor4 = torch.rand(4)
print(tensor3)
print(tensor4)
print(tensor3 == tensor4)

Creating 2 random tensors without the random seed and comparing them
tensor([0.3904, 0.6009, 0.2566, 0.7936])
tensor([0.9408, 0.1332, 0.9346, 0.5936])
tensor([False, False, False, False])

Creating 2 random tensors with random seed and comparing them
tensor([0.8823, 0.9150, 0.3829, 0.9593])
tensor([0.8823, 0.9150, 0.3829, 0.9593])
tensor([True, True, True, True])


La începutul acestui curs spuneam că o rețea neuronală poate fi alcătuită din o mulțime de tensori, iar între acești tensori există numeroase calcule, numeroase computații. Aceste calcule sunt mult mai rapide pe un GPU (placă grafică) deoarece acestea sunt special concepute pentru a realiza calcule numerice extrem de rapid. Din acest motiv, PyTorch ne permite să rulăm cod pe un `GPU` pentru a face un improvement de speed la funcționalitatea codului.

In [3]:
torch.cuda.is_available()

False