# Tensors Operations

În lecția precedentă am învățat cum amune putem să specificăm tipul de date atunic când creem un tensor, cum să modificăm tipul de date dintr-un tensor existent, care este metoda (parametrii utilizați) cea mai des utilizată de a crea tensori și care sunt atributele care ne ajutăm să aflăm informații utile despre tensor (informații care pot să ne ajute la depistarea erorilor). O să facem o scurtă recapitulare a acestor noțiuni.

In [5]:
# import PyTorch
import torch

# creating a random tensor with float16 as datatype
random_tensor = torch.rand(size=(3, 5), dtype=torch.float16)
print(random_tensor)

# printing the datatype stored by the tensor
print(f'random_tensor datatype: {random_tensor.dtype}')

# converting the datatype from float16 to float32
random_tensor_32 = random_tensor.type(torch.float32)

# printing the datatype stored by the new tensor
print(f'random_tensor_32 datatype: {random_tensor_32.dtype}')

# printing the tensor to see if they have the same values
print(f'random_tensor: \n{random_tensor}')
print(f'random_tensor_32: \n{random_tensor_32}')

# the most used way to create tensor
new_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16, device=None, requires_grad=False)


tensor([[0.1050, 0.4912, 0.4097, 0.7607, 0.4731],
        [0.2891, 0.7427, 0.8770, 0.7612, 0.4912],
        [0.5508, 0.0771, 0.6006, 0.6616, 0.4951]], dtype=torch.float16)
random_tensor datatype: torch.float16
random_tensor_32 datatype: torch.float32
random_tensor: 
tensor([[0.1050, 0.4912, 0.4097, 0.7607, 0.4731],
        [0.2891, 0.7427, 0.8770, 0.7612, 0.4912],
        [0.5508, 0.0771, 0.6006, 0.6616, 0.4951]], dtype=torch.float16)
random_tensor_32: 
tensor([[0.1050, 0.4912, 0.4097, 0.7607, 0.4731],
        [0.2891, 0.7427, 0.8770, 0.7612, 0.4912],
        [0.5508, 0.0771, 0.6006, 0.6616, 0.4951]])


În lecția curentă o să vedem cum putem să facem anumite operații cu tensor, iar operațiile care pot fi realizate cu tensori sunt următoarele:

1. Adunare (Addition)

2. Scădere (Substraction)

3. Înmulțire per element (Multiplication element-wise)

4. Împărțire (Division)

5. Înmulțire de matrici (Matrix Multiplication)

O să trecem pe rând prin fiecare ca să observăm comportamentul. Putem să utilizăm semnele aritmetice pentru astfel de operații, dar PyTorch ne pune la dispoziție și o serie de funcții speciale prin care putem să facem asta. Pentru început să creem un tensor și să folosim operațiile simple cu semnele aritmetice

In [6]:
# creating a tensor
tensor = torch.tensor([1, 2, 3])

In [7]:
# addition of a tensor
tensor + 10

tensor([11, 12, 13])

Dacă avem un tensor (care conține mai multe elemente) și se realizează o operație aritmetică cu o singură valoare cu acel tensor, atunci fiecare element din cadrul acelui tensor o să treacă prin operație aritmetică cu valoarea respectivă. Inițial am avut un tensor cu valorile 1, 2 și 3, iar după ce am adunat valoarea 10 pentru acest tensor, fiecare element din acesta a fost adunat cu 10, prin urmare la final avem valorile 11, 12 și 12. La fel se întâmplă cu fiecare operație aritmetică

In [8]:
# substraction of a tensor
tensor - 10

tensor([-9, -8, -7])

In [9]:
# multiplication of a tensor
tensor * 10

tensor([10, 20, 30])

In [10]:
# division of a tensor
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

După cum spuneam, PyTorch ne pune la dispoziție și o serie de metode speciale prin care putem să facem aceste operații.

- Addition = `torch.add()`

- Substraction = `torch.sub()`

- Multiplication = `torch.mul()`

- Division = `torch.div()`

Aceste metode iau ca și prim parametru tensor-ul asupra căruia dorim să facem aceste operații, iar ca și a doua valoare o să ia valoarea cu care dorim să realizăm această operație aritmetică

In [16]:
# addition
print(f'Addition using torch.add(): {torch.add(tensor, 10)}')

# substraction
print(f'Substraction using torch.sub(): {torch.sub(tensor, 10)}')

# Multiplication
print(f'Multiplication using torch.mul(): {torch.mul(tensor, 10)}')

# Division
print(f'Division using torch.div(): {torch.div(tensor, 10)}')

Addition using torch.add(): tensor([11, 12, 13])
Substraction using torch.sub(): tensor([-9, -8, -7])
Multiplication using torch.mul(): tensor([10, 20, 30])
Division using torch.div(): tensor([0.1000, 0.2000, 0.3000])


Atunci când creem o rețea neuronală, aceste tipuri de operații apar destul de des între tensorii cu care se lucrează, de aceea este bine să știm cum funcționează. Cea mai comună operație însă între tensori este cea de 'Matrix Multiplication', care reprezintă și un complex puțin mai complicat și o să ne ocupăm de el în următoarea parte

## Recapitulare

În cadrul acestei secțiuni am învățat următoarele:

1. Cum funcționează partea de operații matematice cu tensori și cum putem să le realizăm

    - Addition

    ```python
    import torch

    tensor = torch.tensor(1, 2, 3)
    tensor + 10
    torch.add(tensor, 10)
    ```

    - Substraction
    ```python
    import torch

    tensor = torch.tensor(1, 2, 3)
    tensor - 10
    torch.sub(tensor, 10)
    ```

    - Multiplication
    ```python
    import torch

    tensor = torch.tensor(1, 2, 3)
    tensor * 10
    torch.mul(tensor, 10)
    ```

    - Division
    ```python
    import torch

    tensor = torch.tensor(1, 2, 3)
    tensor / 10
    torch.div(tensor, 10)
    ```