După cum spuneam, Utilizând un MacBook nu putem să utilizăm și un GPU pentru a experimenta tot ce ține de partea de CPU și GPU utilizând PyTorch. De asta o să utilizăm `Google Colab` pentru a utiliza un GPU oferit gratis de către ei. În acest notebook o să recapitulăm cum putem verifica dacă avem disponibil un GPU, câte GPU-uri avem la dispoziție și cum să mutăm un tensor de pe CPU pe GPU și invers

In [4]:
# importing the library
import torch

Acuma o să verificăm dacă avem la dispozițite o placă video pe care să o folosim.

In [5]:
# verifying if there is a GPU available
torch.cuda.is_available()

True

Din moment ce avem returnat 'True' asta înseamnă că avem la dispoziție un GPU pe care am putea să îl utilizăm. O să creem acea variabilă **device** acuma prin care o să precizăm să folosim placa grafică dacă este disponibilă, iar dacă aceasta nu este disponibilă o să folosim un procesor (CPU)

In [6]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

'cuda' înseamnă că avem la dispoziție un GPU și putem să îl folosim. O să verificăm acuma și numărul de GPU pe care îl avem la dispoziție

In [7]:
torch.cuda.device_count()

1

O singură placă video avem la dispoziție, dar putem să ne utilizăm de aceasta pentru a exeprimenta. Următorul pas pe care o să îl facem, o să creem un tensor. După cum spuneam atunci când creem un tensor, acesta se creează automat pe CPU

In [8]:
tensor = torch.tensor([1,2, 3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

Atunci când creem tensor, putem să îi specificăm în momentul în care îl creem dacă să fie creat pe CPU sau pe GPU prin utilizarea argumentului `device` în momentul în care îl creem

In [12]:
tensor2 = torch.tensor([1, 2, 3], device='cpu')
tensor2, tensor2.device

(tensor([1, 2, 3]), device(type='cpu'))

O să trecem acuma la partea în care o să trecem un tensor de pe CPU pe GPU. Știm că putem să facem asta utilizând comanda 'torch.Tensor.to()' căruia îi specificăm device-ul pe care dorim să mutăm tensor-ul respectiv

In [13]:
tensor_on_gpu = tensor.to(device)

In [14]:
tensor_on_gpu, tensor_on_gpu.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

Din moment ce am avut la dispoziție un GPU și am mutat un tensor de pe CPU pe GPU, acuma când accesăm atributul de **device** acesta ne afișează faptul că acum acest tensor se află acuma pe o placă grafică. De asemnea ne este returnat și index-ul acelei plăci grafice care este util în momentul în care lucrăm cu mai multe plăci grafice.

În continuare o să încercăm să transformăm un tensor care este pe GPU într-un array din NumPy pentru a vedea cum arată și altă eroare comună din PyTorch, și anumea cea în care **tensorii nu se găsesc pe același device**

In [15]:
tensor_on_gpu_to_numpy = tensor_on_gpu.numpy()

TypeError: ignored

După cum se poate observa, când încercăm să transformăm un tensor ce se găsește pe GPU într-un array din NumPy avem o eroare care ne spune că nu putem converti un tensor ce se găsește pe GPU într-un array de NumPy. Din fericire, PyTorch ne afișează și rezolvarea acestei erori, și anume trebuie să utilizăm metoda `torch.Tensor.cpu()` pentru a muta un tensor înapoi pe CPU, iar abia după putem să îl convertim într-un array de NumPy

In [16]:
tensor_on_gpu_to_numpy = tensor_on_gpu.cpu().numpy()
tensor_on_gpu_to_numpy

array([1, 2, 3])

Putem să vedem că acuma am reușit să transformăm acel tensor într-un array din NumPy după ce l-am mutat de pe GPU pe CPU.

Cam așa arată codul și funcționează atunci când avem la dispoziție un GPU pe care să îl folosim.