# Selecting data - Indexing

Data trecută ne-am uitat peste anumite modalități prin care putem modifica shape-ul unui tensor, iar această necesitate de a modifica forma pe care o are un tensor vine din apariția extrem de deasă a erorii care ne duce către forma pe care o are un anumit tensor. O să facem o scurtă recapitulare a acestor metode

In [17]:
# importing PyTorch
import torch

# creating tensor to work with
tensor = torch.arange(1., 10.)

# reshaping tensors
print(f'\n----------RESHAPING----------')
print(f'Initail tensor shape: {tensor.shape}')
print(f'Reshaped tensor shape: {tensor.reshape(1, 9).shape}')
print(f'Reshaped tensor v2 shape: {tensor.reshape(3, 3).shape}')


# creating a view of a tensor
print(f'\n----------VIEW----------')
print(f'Original tensor shape: {tensor.shape}')
print(f'View tensor shape: {tensor.view(1, 1, 9).shape}')
print(f'A view shares the same memory as the tensor, any modification in the view will modify the tensor')

# stacking tensors
print(f'\n----------STACKING----------')
print(f'tensor to be stacked: \n{tensor}')
print(f'tensor stacked 4 times vertically: \n{torch.stack([tensor, tensor, tensor, tensor], dim=0)}')
print(f'tensor stacked 4 times horizontally: \n{torch.stack([tensor, tensor, tensor, tensor], dim=1)}')

# squeezing tensors
tensor1 = tensor.reshape(1, 1, 9)
print(f'\n----------SQUEEZING----------')
print(f'Original tensor before squeezing shape: {tensor1.shape}')
print(f'Squeezed tensor after squeezing shape: {tensor1.squeeze().shape}')

# unsqueezing tensors
print(f'\n----------UNSQUEEZING----------')
print(f'Original tensor before unsqueezing shape: {tensor.shape}')
print(f'Unsqueezed tensor after unsqueezing shape: {tensor.unsqueeze(dim=1).shape}')

# permuting tensors
print(f'\n----------PERMUTE----------')
image_tensor = torch.rand(244, 212, 3)
print(f'Original tensor shape: {image_tensor.shape}')
print(f'Permuted tensor shape: {image_tensor.permute(2, 0, 1).shape}')




----------RESHAPING----------
Initail tensor shape: torch.Size([9])
Reshaped tensor shape: torch.Size([1, 9])
Reshaped tensor v2 shape: torch.Size([3, 3])

----------VIEW----------
Original tensor shape: torch.Size([9])
View tensor shape: torch.Size([1, 1, 9])
A view shares the same memory as the tensor, any modification in the view will modify the tensor

----------STACKING----------
tensor to be stacked: 
tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
tensor stacked 4 times vertically: 
tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])
tensor stacked 4 times horizontally: 
tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

----------SQUEEZING----------
Original tensor be

În lecția curentă o să vedem cum putem să accesăm date dintr-un tensor folosind partea de `indexare` din Python. Partea de indexare atunci când lucrăm cu tensori multidimensionali poate fi destul de complicată la început. O să creem un tensor cu trei dimensiuni pentru a putea face partea practică cât mai bine. Indexarea la tenosri se face asemenea cu indexarea din NumPy, iar pentru accesarea elementelor de asemenea se folosește setul de paranteze drepte.

In [20]:
tensor = torch.arange(1, 10).reshape(1, 3, 3)
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [30]:
tensor.ndim, tensor.shape

(3, torch.Size([1, 3, 3]))

Avem tensorul de mai sus, iar pe baza acestui tensor o să lucrăm. Tensorul repectiv are trei dimensiuni, prima având un element, iar restul câte trei elemente. Putem să începem să utilizăm setul de paranteze drepte pentru a realiza indexarea.

In [31]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [32]:
tensor[0].ndim, tensor[0].shape

(2, torch.Size([3, 3]))

Dacă utilizăm un set de paranteze drepte, acestea o să reprezinte prima dimensiune din cadrul acestui tensor, pentru a accesa următoarele dimensiuni putem să mai utilizăm încă un set de paranteze drepte (atâtea seturi de paranteze drepte câte dimensiuni avem). Dacă pentru valoare de la indexare alegem o valoare care depășește limita acelei dimensiuni o să primim o eroare.

In [33]:
tensor[1]

IndexError: index 1 is out of bounds for dimension 0 with size 1

In [34]:
# indexing the first dimension
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [35]:
# indexing the first and second dimensions
tensor[0][1]

tensor([4, 5, 6])

In [36]:
# indexing the first, second and third dimension
tensor[0][1][1]

tensor(5)

O altă modalitate de a utiliza parte de indexare pe o matrice cu mai multe dimensiuni este să utilizăm toate valorile de indexare într-un singur set de parantezse drepte. Acest lucră o să arate cam așa

In [37]:
tensor[0][0]

tensor([1, 2, 3])

In [38]:
tensor[0, 0]

tensor([1, 2, 3])

Deși metoda de indexare este diferită, rezultatul este același. Prima metodă (**tensor[0][0]**) este metoda standard din Python, iar metoda a doua (**tensor[0, 0]**) este metoda utilizată în NumPy. Avantajul folosirii metodei din NumPy este faptul că putem să utilizăm și slicing la acest tip de indexare. Adică atunci când dorim să extragem să zicem toate valorile de la primul element (neinclus) spre final, putem utiliza partea de indexare

In [48]:
tensor[0, 1:]

tensor([[4, 5, 6],
        [7, 8, 9]])

In [45]:
tensor[0][0]

tensor([1, 2, 3])

Utilizând partea de indexare am reușit să extragem din a doua dimensiune toate valorile aflate după primul rând de valori, ceea ce cu indexarea standard din Python nu putem să facem. O să scriem o serie de exerciții pe care este indicat să le rezolvăm pentru a putea înțelege mai bine cum funcționează partea de indexare pentru tensori (utilizând stilul din NumPy)

In [49]:
# Get all values from 0th and 1st dimensions, but only index 1 from 2nd dimension
tensor[:, :, 1]

tensor([[2, 5, 8]])

După cum se poate observa, prin codul de mai sus am extras toate valorile de pe coloana de mijloc, lucru care cu indexarea standard din Python nu puteam să facem.

In [50]:
tensor[:, :]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [51]:
# get all values from 0th dimension, but only index 1 from 1st and 2nd dimension
tensor[:, 1, 1]

tensor([5])

In [52]:
# get index 0 of 0th and 1st dimension and all values of 2nd dimension
tensor[0, 0, :] 

tensor([1, 2, 3])

In [55]:
# grab the 9 value from the tensor
tensor[0, 2, 2]

tensor(9)

In [56]:
# grab the all elements from the last dimension of the tensor
tensor[:, :, 2]

tensor([[3, 6, 9]])

## Recapitulare

În lecția curentă am învățat următoarele:

1. Există două tipuri de indexare pentru tensor

    - Indexare standard din Python

    - Indexare din NumPy

2. Cum să indexăm din prima dimensiune a unui tensor

    ```python
    import torch

    tensor = torch.arange(1, 10).reshape(1, 3, 3)
    tensor[0] # indexing for the 0th dimension --> both Python style and NumPy style
    ```

3. Cum să indexăm din a doua dimensiune a unui tensor

    ```python
    import torch

    tensor = torch.arange(1,10).reshape(1, 3, 3)
    tensor[0][1] # indexing for the 0the and 1st dimension --> Python style
    tensor[0, 1] # indexing for the 0the and 1st dimension --> NumPy style
    ```

4. Cum să idexăm după a treia dimensiune a unui tensor

    ```python
    import torch

    tensor = torch.arange(1, 10).reshape(1, 3, 3)
    tensor[0][0][2] # indexing for the 0the and 1st dimension --> Python style
    tensor[0, 0, 2] # indexing for the 0the and 1st dimension --> NumPy style
    ```

5. Care este diferența dintre indexarea din Python și cea utilizată în NumPy

Indexarea din NumPy ne permite să utilizăm și conceptul de slicing pentru a extrage doar anumite secțiuni dintr-o dimensiune, ceea ce stiul obișnuit de indexare din Python nu ne permite
