# PyTorch Repoducibility

Deoarece NumPy este o librărie atâta de importantă în ceea ce privește partea de computație de numere, de multe ori este necesar să transformăm date dintr-un array de NumPy într-un tensor, sau inver. Asta am învățat lecția trecută

In [5]:
# importing the libraries
import torch
import numpy as np

# creating a numpy array and converting it to torch.tensor
arr1 = np.arange(1., 10.)
tensor1 = torch.from_numpy(arr1).type(torch.float32)
print(arr1, type(arr1))
print(tensor1, type(tensor1))

# creating a tensor and converting it to numpy.ndarray
tensor2 = torch.ones(1, 7)
arr2 = tensor2.type(torch.float64).numpy()
print(tensor2, type(tensor2))
print(arr2, type(arr2))

[1. 2. 3. 4. 5. 6. 7. 8. 9.] <class 'numpy.ndarray'>
tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]) <class 'torch.Tensor'>
tensor([[1., 1., 1., 1., 1., 1., 1.]]) <class 'torch.Tensor'>
[[1. 1. 1. 1. 1. 1. 1.]] <class 'numpy.ndarray'>


Am aflat faptul că o rețea neuronală se folosește de conceptul de 'random' pentru a crea tensor în rețeaua neuronală. Știm că o rețea neuronală începe nu numere random, face computații și calcule pentru acele date, updatează acele numere random pentru a putea reprezenta mai bine datele și continuă cu acest workflow de un anumit număr de ori. Dacă am dori să reproducem un experiment, poate de multe ori nu dorim să avem de a face de fiecare dată cu numere generate random deoarece dorim ca cineva să reproducă un anumit experiment. Noi de exemplu creem o rețea neuronală cu  un anumit tensor cu valori random și obținem un rezultat. Îi spunem după cuiva să încerce acest cod, dar deoarece se folosesc numere random o să ajungă la alte rezultate, alte valori, ceea ce nu ete tocmai bine. Pentru a reduce acest crearea de numere random în tensori se va folosi conceptul de `random seed` pentru rețelele neuronale din PyTorch (asemănător cu **random_seed** din scikit-learn)

O să creem doi tensor folosind **torch.rand()** și o să vedem că aceștia o să fie diferiți (de fiecare dată când se creează un tensor random, teoretic acesta conține valori random, diferite de valorile altui tensor creat tot prin aceeași metodă).

In [6]:
# importing the library
import torch

# creating 2 random tensors
tensor_1 = torch.rand(3, 4)
tensor_2 = torch.rand(3, 4)

print(tensor_1)
print(tensor_2)
print(tensor_1 == tensor_2)

tensor([[0.2301, 0.8698, 0.8963, 0.0794],
        [0.6049, 0.6000, 0.4100, 0.7845],
        [0.4655, 0.0651, 0.4787, 0.4174]])
tensor([[0.0448, 0.3523, 0.4317, 0.7283],
        [0.8461, 0.2626, 0.3909, 0.9386],
        [0.4326, 0.6846, 0.2328, 0.1599]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


Am creat acei doi tensori, iar la final i-am și comparat. Evident, din moment ce i-am creat cu random, aceștia sunt diferiți și au valori diferite, prin urmare se retunrează False la comparația dintre cei doi. În continuare o să ne folosim de conceptul de `random seed` pentru a crea doi tensori random, dar pe care putem să îi reproducem. Pentru a folosi acest concept o să ne creem o varaibilă căreia o să îi atribuim ca și valoare un număr (această variabilă o să fie o variabilă constantă și o să poarte denumirea de **RANDOM_SEED**), iar acea valoare o să o oferim ca și parametru pentru metoda `torch.manual_seed()`

In [7]:
# creating a constant variable
RANDOM_SEED = 42

# setting the seed for PyTorch
torch.manual_seed(RANDOM_SEED)

Din moment ce am stabilit acest seed, o să creem acuma alți doi tensori pentru a vedea cum sunt creați acuma și dacă sunt la fel sau nu

**NOTE** - pentru ca acest seed să funcționeze trebuie să fie în aceeași celulă unde se creează și tensorii

In [11]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

tensor_3 = torch.rand(3, 4)
tensor_4 = torch.rand(3, 4)

print(tensor_3)
print(tensor_4)
print(tensor_3 == tensor_4)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


**Upps!!** Spuneam că atunci când utilizăm acest seed, ar trebui să avem aceleași date când se creează un tensor folosind **torch.rand()**. Motivul pentru care acești doi tensori nu sunt identici este faptul că acest seed funcționează doar pentru o utilizare a metodei random. Dacă dorim să avem mai mulți tensori identici creți cu 'torch.rand()' atunci trebuie să apelăm metoda de `torch.manual_seed()` înainte de fiecare utilizare a metode `torch.rand()`

In [13]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
tensor_5 = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
tensor_6 = torch.rand(3, 4)

print(tensor_5)
print(tensor_6)
print(tensor_5 == tensor_6)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Acum că am utiliza metoda `torch.manual_seed(RANDOM_SEED` înainte de a crea fiecare tensor random, aceștia sunt identici deoarece s-a folosit același seed la algoritmul de generare de numere random

## Recapitulare

În această lecție am învățat:

1. Cum să setăm un random seed în PyTorch (poartă denumirea de 'torch.manual_seed()'). Trebuie setat înainte de fiecare utilizare a metodei 'torch.rand()'

```python

import torch

# creating the constant random seed variable
RANDOM_SEED = 42

# setting the seed to PyTorch
torch.manual_seed(RANDOM_SEED)

# creating a 'random' tensor
tensor = torch.rand(3, 4)

# we need to set the seed again to create another tensor identical
torch.manual_seed(RANDOM_SEED)
tensor1 = torch.rand(3, 4)
```